### ISSUE TITLE
Not the first Blooket hack

### ISSUE THREAD

**Issue by GunnerBasil** [kgsensei/BlooketHack#10]
I really hate self promotions, but I believe I published my cheat 9 days earlier.

![image](https://user-images.githubusercontent.com/57513430/120913667-f59a9300-c655-11eb-97f2-dfd8ff19ed3a.png)
![image](https://user-images.githubusercontent.com/57513430/120913671-f7fced00-c655-11eb-9955-d406d9d88893.png)

**Comment by kgsensei** [comment]
My b, I'll change it.
