### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SamuelLim1019** [kgsensei/BlooketHack#11]
it always stops bcs of an unknown error

**Comment by kgsensei** [comment]
If you run it through command prompt it should log an error, can you give me that error?
Also, have you installed Python, if so, what version?
And, does this command `pip` work in command prompt?

**Comment by SamuelLim1019** [comment]
Error: Unknown Error While Joining.

**Comment by SamuelLim1019** [comment]
> If you run it through command prompt it should log an error, can you give me that error?
Error: Unknown Error While Joining.
> Also, have you installed Python, if so, what version?
Python 3.9
> And, does this command `pip` work in command prompt?
yes

**Comment by kgsensei** [comment]
Was there a chrome window that opened up?
What happened in that chrome window?

**Comment by SamuelLim1019** [comment]
> Was there a chrome window that opened up?
yes
> What happened in that chrome window?
the app inserted the blooket room code into the window then crashed

**Comment by kgsensei** [comment]
Alright it seems to me that there is an issue with entering the game name or game pin. I will look into the issue later today. Also try using a different game pin or name.

**Comment by SamuelLim1019** [comment]
ok
