### ISSUE TITLE
editVarbile.py not working

### ISSUE THREAD

**Issue by glixzzy** [kgsensei/BlooketHack#2]
editVarible.py is broken doesn't even work and blooket changed their api to https://api.blooket.com/

**Comment by kgsensei** [comment]
Sorry, I didn't realize it was broken.

I will start working on this project again and hopefully get that working.
I must admit, that's a feature I want working too.

**Comment by kgsensei** [comment]
I updated the URL and set the right PUT prams. For some reason it said that was unauthorized though.
All the other features in this cheat should still be functional but I'm not sure I can get this to work.
