### ISSUE TITLE
How to use it I still not understand 👍 

### ISSUE THREAD

**Issue by moonislight6000** [kgsensei/BlooketHack#20]
I download Python 3.10 and double click the main.py file already what to do next?

**Comment by kgsensei** [comment]
Can you download python 3.7? I dont think 3.10 works with this.

**Comment by kgsensei** [comment]
And be sure to check the add to path option on the installer if you can.

**Comment by moonislight6000** [comment]
> And be sure to check the add to path option on the installer if you can.
Ok Thanks I will try

**Comment by moonislight6000** [comment]
> And be sure to check the add to path option on the installer if you can.

Um when I double click the main.py file it just shows a screen and then it gone

**Comment by kgsensei** [comment]
Can you send a screenshot?

**Comment by moonislight6000** [comment]
> Can you send a screenshot?

Sorry I can't

**Comment by moonislight6000** [comment]
![image](https://user-images.githubusercontent.com/95170742/143969248-d258e467-4bf5-4365-b4d8-d7de939a9fbf.png)

**Comment by moonislight6000** [comment]
This is the screen looks like
![image](https://user-images.githubusercontent.com/95170742/144023371-e028fa76-6a4a-423d-a7b8-7cd789dbf457.png)

**Comment by kgsensei** [comment]
Can you find out what version of Chrome your using?

**Comment by moonislight6000** [comment]
> Can you find out what version of Chrome your using?

Version 96.0.4664.45

**Comment by kgsensei** [comment]
What you probably need to do is find the chromedriver file that matches with your browser.

Just look up chrome web driver version 96, that is the only number that should matter. If that's a little too much for you then you can also use glizzxys blooket hack.

It uses only javascript and is very user friendly, not hard to set up.
