### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by DBOSAM** [kgsensei/BlooketHack#21]
It doesn't let me inspect blooket can we find another way?

**Comment by kgsensei** [comment]
Can you please elaborate a little?
Also, do you use a school computer?

**Comment by DBOSAM** [comment]
yes

**Comment by kgsensei** [comment]
Sometimes on school computers inspect will be blocked. At my school I bypassed this by using a different browser. You can typically install other browsers without to many issues.

If you don't want to install a new browser you could try to use edge.

**Comment by TopDownUnder** [comment]
If you're on a computer with Windows 10, Edge should already be installed. If you're using a Chromebook, then you're kinda out of luck

**Comment by DBOSAM** [comment]
Cool, thanks!
