### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by PJG3912** [kgsensei/BlooketHack#22]
Hi, I need a bit help II have crome matched and have it installed what now?

**Comment by kgsensei** [comment]
Run the file.

**Comment by cookiescakescream** [comment]
run the file and it should work

**Comment by Dogwaterzx** [comment]
@bigguystevieb1 you copied your hacks from school cheats lol stop bragging that you made them yourselves.

**Comment by bigguystevieb1** [comment]
@Dogwaterzx  i did though

**Comment by kgsensei** [comment]
That's not exactly a flex.

**Comment by Snowflake-Coder-H2o** [comment]
> @Dogwaterzx i did though

LMAO you didnt code anything. You stole my hacks awhile ago. You steal people's code and claim it as yours. Get good at coding them you can talk about people not coding their own hacks. @kgsensei he has made all of his hacks.

**Comment by Dogwaterzx** [comment]
LMAO same could be said for you.  I know how to code games with LUA lmao.
