### ISSUE TITLE
Error: A device attached to the system is not functioning.

### ISSUE THREAD

**Issue by ConnBots** [kgsensei/BlooketHack#3]
I decided to test thing for about a week or 2 now, only thing that happens is it gives me that error but displays the "Press enter to start hack" and doesn't do anything after you press enter. 

I don't know if this is just because it needs to be on standard blooket and not Cafe, TD, Factory, etc 

![image](https://user-images.githubusercontent.com/76829751/117167908-b0a0e980-ad95-11eb-9246-b17678d1a116.png)

![image](https://user-images.githubusercontent.com/76829751/117167924-b4cd0700-ad95-11eb-9552-52c536fbd4ba.png)

**Comment by ConnBots** [comment]
Also I'm running this on Python 3.7.7 Through the Command Prompt

**Comment by kgsensei** [comment]
Thank you for pointing this out. It appears that the cheat was only optimized for a few of the gamemodes. I will work to update this accordingly.

**Comment by kgsensei** [comment]
I just updated the blooket cheat and it is now functional for the factory gamemode.

Working on TD Next.

**Comment by kgsensei** [comment]
Café, Tower Defense and Factory all work now.
Thank you for pointing this issue out.

I will continue to add support for new gamemodes.
