### ISSUE TITLE
trouble downloading it

### ISSUE THREAD

**Issue by kingzr26** [kgsensei/BlooketHack#4]
i dont know how to get the hack working, and also, do you get all of the books?

**Comment by kgsensei** [comment]
I have not added a way to give all of the Blooks yet, though it is being worked on.
++++++++++++++++++++++++++++++++++
To download the hack you must click the code button and then click, download zip.
![image](https://user-images.githubusercontent.com/60828719/117211160-a814d700-adc6-11eb-93a3-8368d346318b.png)
Second you must extract the files. Ignore all the file options and just click extract.
![image](https://user-images.githubusercontent.com/60828719/117211326-d85c7580-adc6-11eb-8ada-41315431f672.png)
Third you must install python from this link: [Python Download](https://www.python.org/downloads/release/python-379/)
Pick the python type matching what you need:
![image](https://user-images.githubusercontent.com/60828719/117211520-1a85b700-adc7-11eb-8416-f3152d92bbd5.png)
Fourth you need to copy the location that the Blooket Hack files where extracted.
![image](https://user-images.githubusercontent.com/60828719/117211619-4143ed80-adc7-11eb-8b82-79568a6d474f.png)
Fifth you must open command prompt and type `cd <Location you copied>`, Like so:
![image](https://user-images.githubusercontent.com/60828719/117211775-718b8c00-adc7-11eb-86af-2666d1aedb15.png)
Then press enter for it to work.
After all that type `python main.py` and enter the required information for the cheat to work.
![image](https://user-images.githubusercontent.com/60828719/117211968-af88b000-adc7-11eb-811a-262f0865419c.png)
Then your done.

If you need any help just let me know.

**Comment by Minesraft2** [comment]
I ended up getting this message
![image](https://user-images.githubusercontent.com/49218878/117229975-ac9ab900-ade1-11eb-8449-72df33fb571f.png)

**Comment by kgsensei** [comment]
Good to know, the install commands are listed on the `readme.md` file. Hope that helps.
