### ISSUE TITLE
Problem with starting it.

### ISSUE THREAD

**Issue by firemanwilll14** [kgsensei/BlooketHack#5]
After I enter my name and code and press enter i get this error 
![image](https://user-images.githubusercontent.com/66516110/117221403-82321580-ae4c-11eb-820d-301a644b5f25.png)

**Comment by kgsensei** [comment]
What you need to do here is find the location the chrome.exe on your computer and change the chrome path in this line to the path you found.
```options.binary_location=r'C:\Program Files\Google\Chrome\Application\chrome.exe'```
To:
```options.binary_location=r'<Your Path To Chrome EXE>'```

**Comment by firemanwilll14** [comment]
Hello, everything starts up all good now, but when i am at the screen on booklet to answer questions, the CMD says "Press enter to start cheat" but when I do nothing happens?

![image](https://user-images.githubusercontent.com/66516110/117236557-4018cc00-ae6c-11eb-9ba2-468175ca2b00.png)

**Comment by firemanwilll14** [comment]
That was when I was trying factory, I switched over to classic and after I pressed enter on classic, all the cmd would do was read out the different answers for all the different questions on loop without stopping.

**Comment by kgsensei** [comment]
That means its working the way it should. It detects the current answer by using the text in the problem, if every single question is the same it will break. Try a blooket game with different questions if you aren't already.

I recently patched an issue where Factory didn't work so I would recommend installing the `main.py` file again. Nothing else is needed though.

Some game modes aren't added yet, that's what nothing happening means.
